In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from os import listdir
from os.path import isfile, join

In [18]:
path = 'tripdata/divvy/'
tripdataFilenames = [f for f in listdir(path) if isfile(join(path, f))]
print(tripdataFilenames)
print(len(tripdataFilenames))

['Divvy_Trips_2016_04.csv', 'Divvy_Trips_2016_05.csv', 'Divvy_Trips_2015_07.csv', 'Divvy_Trips_2016_Q3.csv', 'Divvy_Trips_2017_Q2.csv', 'Divvy_Trips_2014-Q4.csv', 'Divvy_Trips_2016_Q4.csv', 'Divvy_Trips_2016_06.csv', 'Divvy_Trips_2017_Q1.csv', 'Divvy_Trips_2014_Q1Q2.csv', 'Divvy_Trips_2014-Q3-0809.csv', 'Divvy_Trips_2014-Q3-07.csv', 'Divvy_Trips_2015-Q2.csv', 'Divvy_Trips_2015_08.csv', 'Divvy_Trips_2016_Q1.csv', 'Divvy_Trips_2013.csv', 'Divvy_Trips_2015_Q4.csv', 'Divvy_Trips_2015-Q1.csv', 'Divvy_Trips_2015_09.csv']
19

In [45]:
dtype={'trip_id': int, 'starttime': str, 'stoptime': str, 'start_time': str, 'end_time': str, 'bikeid': int, 'tripduration': int, 
       'from_station_id': int, 'from_station_name': str, 'to_station_id': int, 'to_station_name': str, 
       'usertype': str, 'gender': str, 'birthday': str, 'birthyear': str}

tripdataFrames = [
    pd.read_csv(path + filename, dtype=dtype).rename(columns = {'start_time':'starttime', 'end_time':'stoptime', 'birthday':'birthyear'}) 
    for filename in tripdataFilenames]

In [46]:
tripdataFrame = pd.concat(tripdataFrames)
tripdataFrame = tripdataFrame.rename(columns = {'from_station_id':'start station id', 'to_station_id':'end station id'})

In [47]:
tripdataFrame

,trip_id,starttime,stoptime,bikeid,tripduration,start station id,from_station_name,end station id,to_station_name,usertype,gender,birthyear
0,9379901,4/30/2016 23:59,5/1/2016 0:11,21,733,123,California Ave & Milwaukee Ave,374,Western Ave & Walton St,Subscriber,Male,1982
1,9379900,4/30/2016 23:58,5/1/2016 0:07,3583,556,349,Halsted St & Wrightwood Ave,165,Clark St & Grace St,Subscriber,Male,1991
2,9379899,4/30/2016 23:58,5/1/2016 0:02,4557,253,59,Wabash Ave & Roosevelt Rd,273,Michigan Ave & 18th St,Subscriber,Male,1984
3,9379898,4/30/2016 23:54,5/1/2016 0:08,2443,802,289,Wells St & Concord Ln,199,Wabash Ave & Grand Ave,Subscriber,Male,1978
4,9379897,4/30/2016 23:52,5/1/2016 0:11,50,1146,239,Western Ave & Leland Ave,227,Southport Ave & Waveland Ave,Customer,NaN,NaN
5,9379896,4/30/2016 23:49,5/1/2016 0:11,1676,1291,239,Western Ave & Leland Ave,227,Southport Ave & Waveland Ave,Customer,NaN,NaN
6,9379895,4/30/2016 23:46,4/30/2016 23:54,3619,451,56,Desplaines St & Kinzie St,186,Ogden Ave & Race Ave,Subscriber,Male,1988
7,9379894,4/30/2016 23:45,5/1/2016 0:18,2200,1954,129,Blue Island Ave & 18th St,36,Franklin St & Jackson Blvd,Subscriber,Male,1992
8,9379893,4/30/2016 23:38,4/30/2016 23:42,693,226,300,Broadway & Barry Ave,299,Halsted St & Roscoe St,Subscriber,Male,1984
9,9379892,4/30/2016 23:37,4/30/2016 23:53,1627,954,287,Franklin St & Monroe St,56,Desplaines St & Kinzie St,Subscriber,Male,1987
10,9379891,4/30/2016 23:36,4/30/2016 23:42,903,369,131,Lincoln Ave & Belmont Ave,308,Seeley Ave & Roscoe St,Subscriber,Male,1991
11,9379890,4/30/2016 23:35,4/30/2016 23:38,1850,201,318,Southport Ave & Irving Park Rd,240,Sheridan Rd & Irving Park Rd,Subscriber,Male,1974
12,9379889,4/30/2016 23:32,4/30/2016 23:41,1806,559,301,Clark St & Schiller St,143,Sedgwick St & Webster Ave,Subscriber,Female,1986
13,9379884,4/30/2016 23:26,4/30/2016 23:37,4163,651,414,Canal St & Taylor St,205,Paulina St & 18th St,Subscriber,Female,1982
14,9379883,4/30/2016 23:24,4/30/2016 23:44,2647,1184,243,Lincoln Ave & Leavitt St,458,Broadway & Thorndale Ave,Subscriber,Male,1982
15,9379882,4/30/2016 23:23,4/30/2016 23:49,2448,1573,47,State St & Kinzie St,303,Broadway & Cornelia Ave,Subscriber,Male,1980
16,9379881,4/30/2016 23:22,4/30/2016 23:27,1903,303,199,Wabash Ave & Grand Ave,142,McClurg Ct & Erie St,Subscriber,Male,1987
17,9379876,4/30/2016 23:14,4/30/2016 23:35,1933,1249,163,Damen Ave & Clybourn Ave,476,Kedzie Ave & Leland Ave,Subscriber,Male,1984
18,9379874,4/30/2016 23:15,4/30/2016 23:18,2053,217,417,Cornell Ave & Hyde Park Blvd,322,Kimbark Ave & 53rd St,Subscriber,Male,1986
19,9379873,4/30/2016 23:13,4/30/2016 23:17,1417,254,13,Wilton Ave & Diversey Pkwy,319,Greenview Ave & Diversey Pkwy,Subscriber,Male,1990
20,9379869,4/30/2016 23:10,4/30/2016 23:14,2858,258,176,Clark St & Elm St,291,Wells St & Evergreen Ave,Subscriber,Male,1994
21,9379868,4/30/2016 23:06,4/30/2016 23:13,1547,384,490,Troy St & Elston Ave,491,Talman Ave & Addison St,Subscriber,Male,1981
22,9379866,4/30/2016 23:02,4/30/2016 23:05,3969,196,326,Clark St & Leland Ave,253,Clifton Ave & Lawrence Ave,Subscriber,Male,1989
23,9379863,4/30/2016 22:59,4/30/2016 23:07,3031,483,322,Kimbark Ave & 53rd St,426,Ellis Ave & 60th St,Subscriber,Male,1994
24,9379859,4/30/2016 22:55,4/30/2016 23:00,2707,285,322,Kimbark Ave & 53rd St,419,Lake Park Ave & 53rd St,Subscriber,Male,1960
25,9379858,4/30/2016 22:55,4/30/2016 23:00,4298,275,299,Halsted St & Roscoe St,232,Pine Grove Ave & Waveland Ave,Subscriber,Male,1978
26,9379856,4/30/2016 22:52,4/30/2016 22:58,4663,340,210,Ashland Ave & Division St,86,Eckhart Park,Subscriber,Female,1990
27,9379855,4/30/2016 22:52,4/30/2016 22:57,4297,308,298,Lincoln Ave & Belle Plaine Ave,242,Damen Ave & Leland Ave,Subscriber,Female,1988
28,9379854,4/30/2016 22:51,4/30/2016 22:54,192,175,234,Clark St & Montrose Ave,246,Ashland Ave & Belle Plaine Ave,Subscriber,Male,1992
29,9379852,4/30/2016 22:48,4/30/2016 22:52,1958,262,107,Desplaines St & Jackson Blvd,286,Franklin St & Quincy St,Subscriber,Male,1987
...,...,...,...,...,...,...,...,...,...,...,...,...
427065,7221444,9/1/2015 0:20,9/1/2015 0:24,2524,244,245,Clarendon Ave & Junior Ter,256,Broadway & Sheridan Rd,Subscriber,Male,1990
427066,7221443,9/1/2015 0:19,9/1/2015 0:46,3242,1632,324,Stockton Dr & Wrightwood Ave,35,Streeter Dr & Illinois St,Customer,NaN,NaN
427067,7221442,9/1/2015 0:19,9/1/2015 0:47,4773,1659,324,Stockton Dr & Wrightwood Ave,35,Streeter Dr & Illinois St,Customer,NaN,NaN
427068,7221441,9/1/2015 0:19,9/1/2015 0:29,1613,593,198,Green St (Halsted St) & Madison St,86,Eckhart Park,Subscriber,Male,1988
427069,7221440,9/1/2015 0:18,9/1/2015 0:37,623,1117,35,Streeter Dr & Illinois St,194,Wabash Ave & Wacker Pl,Customer,NaN,NaN
427070,7221439,9/1/2015 0:18,9/1/2015 0:22,874,251,169,Canal St & Harrison St,77,Clinton St & Madison St,Subscriber,Male,1952
427071,7221438,9/1/2015 0:18,9/1/2015 0:27,4789,506,234,Clark St & Montrose Ave,114,Sheffield Ave & Addison St,Customer,NaN,NaN
427072,7221437,9/1/2015 0:18,9/1/2015 0:37,561,1120,35,Streeter Dr & Illinois St,194,Wabash Ave & Wacker Pl,Customer,NaN,NaN
427073,7221436,9/1/2015 0:18,9/1/2015 0:37,2765,1145,35,Streeter Dr & Illinois St,194,Wabash Ave & Wacker Pl,Customer,NaN,NaN
427074,7221435,9/1/2015 0:17,9/1/2015 0:21,3025,210,342,Wolcott Ave & Polk St,317,Wood St & Taylor St,Subscriber,Female,1989
427075,7221434,9/1/2015 0:17,9/1/2015 0:22,2910,288,304,Broadway & Waveland Ave,312,Clarendon Ave & Gordon Ter,Subscriber,Female,1992
427076,7221433,9/1/2015 0:17,9/1/2015 0:21,738,252,21,Aberdeen St & Jackson Blvd,241,Morgan St & Polk St,Subscriber,Male,1988
427077,7221432,9/1/2015 0:16,9/1/2015 0:33,3178,1028,231,Sheridan Rd & Montrose Ave,326,Clark St & Leland Ave,Subscriber,Female,1984
427078,7221430,9/1/2015 0:14,9/1/2015 0:19,1454,279,60,Dayton St & North Ave,118,Sedgwick St & North Ave,Subscriber,Male,1989
427079,7221429,9/1/2015 0:13,9/1/2015 0:52,103,2341,351,Cottage Grove Ave & 51st St,184,State St & 35th St,Customer,NaN,NaN
427080,7221427,9/1/2015 0:11,9/1/2015 0:19,261,490,59,Wabash Ave & Roosevelt Rd,55,Halsted St & Roosevelt Rd,Subscriber,Male,1976
427081,7221426,9/1/2015 0:10,9/1/2015 0:40,4059,1836,15,Racine Ave & 18th St,118,Sedgwick St & North Ave,Subscriber,Male,1981
427082,7221425,9/1/2015 0:09,9/1/2015 0:15,3220,349,230,Lincoln Ave & Roscoe St,244,Ravenswood Ave & Irving Park Rd,Subscriber,Male,1984
427083,7221424,9/1/2015 0:08,9/1/2015 0:20,4223,742,465,Marine Dr & Ainslie St,462,Ravenswood Ave & Balmoral Ave,Customer,NaN,NaN
427084,7221423,9/1/2015 0:08,9/1/2015 0:25,4542,1026,173,Mies van der Rohe Way & Chicago Ave,210,Ashland Ave & Division St,Subscriber,Male,1976
427085,7221420,9/1/2015 0:06,9/1/2015 0:10,3258,193,91,Clinton St & Washington Blvd,68,Clinton St & Tilden St,Subscriber,Male,1985
427086,7221419,9/1/2015 0:06,9/1/2015 0:11,3554,274,118,Sedgwick St & North Ave,60,Dayton St & North Ave,Subscriber,Male,1982
427087,7221418,9/1/2015 0:05,9/1/2015 0:14,1682,510,464,Damen Ave & Foster Ave,461,Broadway & Ridge Ave,Customer,NaN,NaN
427088,7221417,9/1/2015 0:05,9/1/2015 0:16,1177,651,326,Clark St & Leland Ave,231,Sheridan Rd & Montrose Ave,Subscriber,Female,1984
427089,7221415,9/1/2015 0:03,9/1/2015 0:13,735,580,110,Dearborn St & Erie St,174,Canal St & Madison St,Subscriber,Male,1974
427090,7221414,9/1/2015 0:03,9/1/2015 0:17,2183,824,298,Lincoln Ave & Belle Plaine Ave,472,Lincoln Ave & Winona St,Subscriber,Female,1988
427091,7221412,9/1/2015 0:02,9/1/2015 0:16,2242,849,234,Clark St & Montrose Ave,244,Ravenswood Ave & Irving Park Rd,Customer,NaN,NaN
427092,7221411,9/1/2015 0:01,9/1/2015 0:16,1553,869,234,Clark St & Montrose Ave,244,Ravenswood Ave & Irving Park Rd,Customer,NaN,NaN
427093,7221410,9/1/2015 0:01,9/1/2015 0:29,4366,1664,247,Shore Drive & 55th St,121,Blackstone Ave & Hyde Park Blvd,Customer,NaN,NaN
427094,7221409,9/1/2015 0:00,9/1/2015 0:15,3747,902,228,Damen Ave & Melrose Ave,69,Damen Ave & Pierce Ave,Subscriber,Male,1992

In [48]:
frequencyByStation = tripdataFrame[['start station id','end station id','starttime']].groupby(['start station id','end station id']).count()

In [49]:
frequencyByStation.to_csv('divvy_frequencyByStation.csv')